"""Figure 4 — the Klein quartic as the {7,3} tiling (Riemann-surface lens).
Regular hyperbolic heptagons, 3 around each vertex, generated by the von Dyck
(2,3,7) rotation group. On the genus-3 Klein quartic exactly 24 of these
heptagons close up; its 168 orientation-preserving symmetries meet the Hurwitz
maximum 84(g-1)."""
import numpy as np, sys, math
sys.path.insert(0,'psl168'); sys.path.insert(0,'octonions')
import p168, figkit
from PIL import Image, ImageDraw
from scipy.ndimage import gaussian_filter
import colorsys

def Rot(th): return np.array([[np.exp(1j*th/2),0],[0,np.exp(-1j*th/2)]],complex)
def Trans(v):
    s=1/math.sqrt(1-abs(v)**2); return np.array([[s, s*v],[s*np.conj(v), s]],complex)
def mob(M,z): return (M[0,0]*z+M[0,1])/(M[1,0]*z+M[1,1])
def nrm(M):
    a,b=M[0,0],M[0,1]
    s=math.sqrt((a*np.conj(a)-b*np.conj(b)).real)
    return np.array([[a,b],[np.conj(b),np.conj(a)]],complex)/s
def key(M): z=mob(M,0); return (round(z.real,3),round(z.imag,3))

def heptagons(maxn=600, rmax=0.93):
    Rh=math.acosh(1.0/(math.tan(math.pi/7)*math.tan(math.pi/3))); Re=math.tanh(Rh/2)
    verts=[Re*np.exp(1j*2*math.pi*k/7) for k in range(7)]
    a=Rot(2*math.pi/7); ai=Rot(-2*math.pi/7)
    V0=verts[0]; T=Trans(V0); Ti=Trans(-V0)
    b=T@Rot(2*math.pi/3)@Ti; bi=T@Rot(-2*math.pi/3)@Ti
    gens=[a,ai,b,bi]
    I=np.eye(2,dtype=complex)
    seen={key(I):I}; frontier=[I]; order=[I]
    while frontier and len(seen)<maxn:
        nf=[]
        for M in frontier:
            for g in gens:
                P=nrm(g@M); k=key(P)
                if k not in seen and abs(mob(P,0))<rmax:
                    seen[k]=P; nf.append(P); order.append(P)
        frontier=nf
    return order, verts

def render(W=1500, ss=2):
    Wi=W*ss
    tiles,verts=heptagons()
    base=Image.new("RGB",(Wi,Wi),(4,5,12)); d=ImageDraw.Draw(base,"RGBA")
    cx=cy=Wi/2; sc=Wi*0.49
    def S(z): return (cx+z.real*sc, cy-z.imag*sc)
    # sort far-first so central (big, bright) heptagons draw on top
    tiles=sorted(tiles, key=lambda M: -abs(mob(M,0)))
    for M in tiles:
        c=abs(mob(M,0))
        hue=(0.55 - 0.42*c)%1.0
        r,g,bl=colorsys.hsv_to_rgb(hue,0.6,1.0)
        col=(int(r*255),int(g*255),int(bl*255))
        tv=[mob(M,v) for v in verts]
        bnd=[]
        for k in range(7):
            bnd+=[S(z) for z in p168.geodesic_arc(tv[k],tv[(k+1)%7],n=12)]
        d.polygon(bnd, fill=(col[0],col[1],col[2],16))
        wdt=max(2,int(ss*(1.2+5.0*(1-c))))
        for k in range(7):
            pts=[S(z) for z in p168.geodesic_arc(tv[k],tv[(k+1)%7],n=22)]
            d.line(pts, fill=(col[0],col[1],col[2],235), width=wdt, joint="curve")
    arr=np.asarray(base).astype(np.float32)/255
    g=np.stack([gaussian_filter(arr[...,c],ss*1.0) for c in range(3)],-1)
    arr=1.0-np.exp(-1.3*(arr+0.30*g))
    ys,xs=np.mgrid[0:Wi,0:Wi]; rr=np.hypot(xs-cx,ys-cy)/sc
    arr[rr>1.0]=np.array([0.016,0.018,0.03])
    img=Image.fromarray((np.clip(arr,0,1)*255).astype('uint8'))
    return img.resize((W,W),Image.LANCZOS)

if __name__=="__main__":
    viz=render(1500)
    body=("Bundle the triangles of the previous figure into HEPTAGONS — seven-sided hyperbolic "
          "tiles meeting three at a vertex, the regular tiling {7,3}. This is the natural skin of "
          "the KLEIN QUARTIC, the curve x³y + y³z + z³x = 0, the most symmetric surface of genus 3. "
          "Although the tiling continues forever in the disk, on the quartic itself it wraps around "
          "and closes after exactly 24 heptagons (56 vertices, 84 edges — Euler characteristic "
          "−4 = 2−2·3). Its group of rotational symmetries has order 168 — and that is no "
          "accident: Hurwitz proved no genus-g surface can have more than 84(g−1) such symmetries, "
          "and for g=3 that bound is 84·2 = 168, hit on the nose. PSL(2,7) is the symmetry of the "
          "most symmetric surface there can be at this genus.")
    fig=figkit.caption(viz,"FIGURE 4 · THE KLEIN QUARTIC","The {7,3} tiling — a genus-3 jewel",
                       body,accent=(120,210,235),W=1500)
    figkit.save(fig,"psl168/04_klein_quartic.png")
    print("done",fig.size)
