"""Figure 6 — how the octonions fail to associate (the associator lens).
A worked triple: (e2 e3) e4 = +e5  but  e2 (e3 e4) = -e5. The two groupings
disagree by a sign. Yet every triple ON a Fano line associates: those are the
seven copies of the quaternions H inside O."""
import numpy as np, sys, math
sys.path.insert(0,'octonions')
import octo, figkit
from PIL import Image, ImageDraw

def render(W=1600):
    Hh=1320
    img=Image.new("RGB",(W,Hh),(10,11,19)); d=ImageDraw.Draw(img,"RGBA")
    fbold=figkit.font("DejaVuSans-Bold.ttf",52)
    fop  =figkit.font("DejaVuSans.ttf",46)
    fsm  =figkit.font("DejaVuSans.ttf",33)
    rgb=lambda k,f=1.0:tuple(min(255,int(255*v*f)) for v in octo.UNIT_RGB[k])
    def tokens(cx,y,toks):
        # toks: list of (text, color); measure total, center
        widths=[d.textlength(t,font=fbold if c is not None else fop) for t,c in toks]
        tot=sum(widths)+ (len(toks)-1)*16
        x=cx-tot/2
        for (t,c),wdt in zip(toks,widths):
            f=fbold if c is not None else fop
            a=f.getbbox(t); d.text((x,y-(a[3]-a[1])/2-a[1]),t,font=f,fill=(c if c else (210,216,232)))
            x+=wdt+16
    BL=(225,231,245)
    d.text((90,70),"Two ways to bracket a product of three octonions:",font=fsm,fill=(170,180,205))
    # Track 1
    tokens(W/2,210,[("( ",None),("e₂",rgb(2)),(" · ",None),("e₃",rgb(3)),(" ) · ",None),("e₄",rgb(4)),
                    ("   =   ",None),("e₁",rgb(1)),(" · ",None),("e₄",rgb(4)),
                    ("   =   ",None),("+ e₅",rgb(5))])
    # Track 2
    tokens(W/2,330,[("e₂",rgb(2)),(" · ( ",None),("e₃",rgb(3)),(" · ",None),("e₄",rgb(4)),(" )",None),
                    ("   =   ",None),("e₂",rgb(2)),(" · ",None),("e₇",rgb(7)),
                    ("   =   ",None),("− e₅",rgb(5,0.85))])
    # the disagreement
    d.text((W/2-70,430),"≠",font=figkit.font("DejaVuSans-Bold.ttf",70),fill=(255,120,120))
    tokens(W/2,560,[("associator   [ ",None),("e₂",rgb(2)),(", ",None),("e₃",rgb(3)),(", ",None),
                    ("e₄",rgb(4)),(" ]  =  (",None),("e₂e₃",None),(")",None),("e₄",rgb(4)),(" − ",None),
                    ("e₂",rgb(2)),("(",None),("e₃e₄",None),(")  =  2 ",None),("e₅",rgb(5))])
    # divider
    d.line([(80,660),(W-80,660)],fill=(50,55,72,255),width=3)
    # bottom: mini-Fano of the 7 associative lines (quaternions)
    cxf, cyf, r = 360, 960, 230
    pos={}
    for lab,a in {2:90,4:210,7:330}.items():
        pos[lab]=(cxf+r*math.cos(math.radians(a)), cyf-r*math.sin(math.radians(a)))
    pos[1]=(cxf,cyf)
    pos[6]=tuple((np.array(pos[2])+np.array(pos[4]))/2)
    pos[5]=tuple((np.array(pos[2])+np.array(pos[7]))/2)
    pos[3]=tuple((np.array(pos[4])+np.array(pos[7]))/2)
    for (x,y,z) in [(2,6,4),(2,5,7),(4,3,7),(2,1,3),(4,1,5),(7,1,6)]:
        d.line([pos[x],pos[z]],fill=(255,210,120,160),width=4)
    d.ellipse([cxf-r/2,cyf-r/2,cxf+r/2,cyf+r/2],outline=(255,210,120,160),width=4)
    for k,p in pos.items():
        d.ellipse([p[0]-15,p[1]-15,p[0]+15,p[1]+15],fill=rgb(k),outline=(255,255,255,230),width=2)
    d.text((cxf-150,cyf+r+40),"the 7 lines associate",font=fsm,fill=(255,205,120))
    # right text
    rx=760
    d.text((rx,820),"On a Fano line, three units",font=fop,fill=BL)
    d.text((rx,876),"generate a copy of the",font=fop,fill=BL)
    d.text((rx,932),"quaternions  ℍ  —  associative.",font=fop,fill=BL)
    d.text((rx,1010),"Off a line, they don't:",font=fop,fill=(255,160,160))
    d.text((rx,1066),"7 associative triples,",font=fsm,fill=(180,190,210))
    d.text((rx,1108),"28 non-associative ones.",font=fsm,fill=(180,190,210))
    d.text((rx,1170),"𝕆 keeps only the weaker",font=fsm,fill=(150,160,185))
    d.text((rx,1212),"ALTERNATIVE law: any TWO",font=fsm,fill=(150,160,185))
    d.text((rx,1254),"units always associate.",font=fsm,fill=(150,160,185))
    return img

if __name__=="__main__":
    viz=render(1600)
    body=("Multiplication in 𝕆 depends on where you put the brackets. Take e₂, e₃, e₄: grouping "
          "the first pair gives (e₂e₃)e₄ = e₁·e₄ = +e₅, but grouping the second gives e₂(e₃e₄) = "
          "e₂·e₇ = −e₅. Same three numbers, opposite answers — their associator is 2e₅, not zero. "
          "This is the price the octonions pay for existing at all. The exception is any triple "
          "lying ON a Fano line: those three units close up into a copy of the quaternions ℍ and "
          "DO associate. So among the 35 triples of imaginary units, exactly 7 (the Fano lines) "
          "are associative and 28 are not. What survives is the gentler ALTERNATIVE law — every "
          "sub-algebra generated by just TWO elements is associative — which is what still makes "
          "𝕆 a division algebra.")
    fig=figkit.caption(viz,"FIGURE 6 · NON-ASSOCIATIVITY","Two ways to multiply three octonions",
                       body,accent=(255,130,130))
    figkit.save(fig,"octonions/06_associator.png")
    print("done",fig.size)
