"""
04 — Purpose and Pattern
Inspired by Philosophy StackExchange (from the 2026-07-04 front-page sweep,
carried forward as an also-ran): "Is it 'purpose' which makes human actions
readable?" -- i.e. can you tell, from the trace alone, whether something was
GENERATED for a reason (a short underlying rule) or happened for no reason at
all (irreducible randomness)?

We build the cleanest real answer: a KOLMOGOROV-COMPLEXITY DIPTYCH.

LEFT panel: bytes generated by the shortest possible generator -- "repeat this
fixed short seed forever." The description length of that program is
|seed| + O(log N), independent of the output length N: genuinely LOW
Kolmogorov complexity, however long you let it run.

RIGHT panel: bytes drawn from the operating system's cryptographic entropy
pool (os.urandom) -- as close to "no shorter description exists" as a
computer can produce. Its Kolmogorov complexity is, with overwhelming
probability, within a constant of N itself.

Both are mapped through the *same* curated palette and rendered at the same
resolution, so any visible difference is a property of the bytes, not the
colouring. At a glance they are the same species of static -- the seed's
period (200,000 bytes, far larger than a screen-sized glance, and NOT an
integer multiple of the row width) is invisible to the eye. But a real
general-purpose compressor (LZMA) finds the repeat instantly: the left panel
crushes to a few percent of its size; the right panel does not compress at
all. And -- the piece's second, quieter point -- if you only look at small
LOCAL tiles (far smaller than the seed period), the pattern disappears again:
local compressibility is statistically identical on both sides. The "purpose"
here is a property of the WHOLE trace, invisible to any part of it in
isolation -- readable only in aggregate, exactly like the question that
seeded this piece.

(Caption honesty: an even harder case exists and is NOT shown here -- the
digits of an actual computable constant, e.g. Champernowne's number
0.123456789101112... in binary, are fully deterministic from a one-line
generator ["count up, concatenate"] yet have NO short-range repeat at all, so
LZMA/gzip cannot expose their low complexity either. That case would need a
compressor that already knows to look for counting -- purpose invisible not
just locally, but to any *generic* observer. The repeating-block construction
here is the simplest instance where a standard tool actually reveals the
gap.)
"""
import os
import lzma
import numpy as np
from PIL import Image, ImageDraw, ImageFont, ImageFilter

rng = np.random.default_rng(20260705)

PANEL_W, PANEL_H = 1200, 1600
GUTTER = 160
INFO_H = 340
CANVAS_W = PANEL_W * 2 + GUTTER
CANVAS_H = PANEL_H + INFO_H

PANEL_BYTES = PANEL_W * PANEL_H * 3
PERIOD = 200_000  # << PANEL_BYTES; >> a screen-glance's worth of rows

# ---------------------------------------------------------------------------
# LEFT: low-complexity generator = "repeat this fixed seed forever."
# ---------------------------------------------------------------------------
seed_block = rng.integers(0, 256, size=PERIOD, dtype=np.uint8)
n_repeats = -(-PANEL_BYTES // PERIOD)  # ceil
left_bytes = np.tile(seed_block, n_repeats)[:PANEL_BYTES]

# ---------------------------------------------------------------------------
# RIGHT: genuine OS entropy -- no shorter description than itself.
# ---------------------------------------------------------------------------
right_bytes = np.frombuffer(os.urandom(PANEL_BYTES), dtype=np.uint8)

print(f"panel bytes: {PANEL_BYTES}, period: {PERIOD}, "
      f"rows/period: {PERIOD/(PANEL_W*3):.1f}, repeats/panel: {PANEL_BYTES/PERIOD:.1f}")

# ---------------------------------------------------------------------------
# Compression divergence: whole-panel (should diverge hugely) vs. average
# small-tile (should NOT diverge -- local windows are far smaller than the
# seed period, so the redundancy is invisible locally).
# ---------------------------------------------------------------------------
def compressed_ratio(buf):
    c = lzma.compress(buf.tobytes(), preset=6)
    return len(c) / len(buf)

TILE = 48
tile_bytes = TILE * TILE * 3

def avg_tile_ratio(flat_bytes, n_samples=250):
    ratios = []
    max_start = len(flat_bytes) - tile_bytes
    starts = rng.integers(0, max_start, size=n_samples)
    for s in starts:
        chunk = flat_bytes[s:s+tile_bytes]
        c = lzma.compress(chunk.tobytes(), preset=6)
        ratios.append(len(c) / len(chunk))
    return float(np.mean(ratios))

left_whole = compressed_ratio(left_bytes)
right_whole = compressed_ratio(right_bytes)
left_tile = avg_tile_ratio(left_bytes)
right_tile = avg_tile_ratio(right_bytes)

print(f"LEFT  whole-panel compressed ratio: {left_whole:.4f}")
print(f"RIGHT whole-panel compressed ratio: {right_whole:.4f}")
print(f"LEFT  avg small-tile compressed ratio: {left_tile:.4f}")
print(f"RIGHT avg small-tile compressed ratio: {right_tile:.4f}")

# ---------------------------------------------------------------------------
# Render: curated palette LUT (NOT raw HSV confetti) driven by luminance,
# with a second byte adding fine sparkle. Same transform on both panels.
# ---------------------------------------------------------------------------
ANCHORS = np.array([
    [0.03, 0.02, 0.08],   # near-black indigo (dark)
    [0.10, 0.05, 0.30],   # deep violet
    [0.05, 0.25, 0.45],   # teal-blue
    [0.10, 0.55, 0.50],   # jade
    [0.75, 0.65, 0.20],   # gold
    [0.98, 0.92, 0.75],   # near-white warm
], dtype=np.float64)
N_ANCH = len(ANCHORS)

def palette_lookup(t):
    # t in [0,1]
    pos = np.clip(t, 0, 1) * (N_ANCH - 1)
    i0 = np.floor(pos).astype(int)
    i1 = np.clip(i0 + 1, 0, N_ANCH - 1)
    f = (pos - i0)[..., None]
    return ANCHORS[i0] * (1 - f) + ANCHORS[i1] * f

def render_panel(flat_bytes):
    arr = flat_bytes[:PANEL_BYTES].reshape(PANEL_H, PANEL_W, 3).astype(np.float64)
    lum = arr.mean(axis=2) / 255.0
    sparkle = arr[..., 1] / 255.0
    rgb = palette_lookup(lum)
    rgb = rgb * (0.82 + 0.36 * sparkle[..., None])
    return np.clip(rgb, 0, 1)

left_rgb = render_panel(left_bytes)
right_rgb = render_panel(right_bytes)

canvas = np.zeros((CANVAS_H, CANVAS_W, 3), dtype=np.float64)
canvas[:PANEL_H, :PANEL_W] = left_rgb
canvas[:PANEL_H, PANEL_W+GUTTER:PANEL_W+GUTTER+PANEL_W] = right_rgb
# gutter: dark seam
canvas[:PANEL_H, PANEL_W:PANEL_W+GUTTER] = np.array([0.02, 0.02, 0.03])

out = (np.clip(canvas, 0, 1) * 255).astype(np.uint8)
img = Image.fromarray(out, 'RGB')

# ---------------------------------------------------------------------------
# Info band: 4 bars (left-whole, left-tile, right-whole, right-tile) plus
# small captions -- the numbers ARE part of the piece.
# ---------------------------------------------------------------------------
draw = ImageDraw.Draw(img)
try:
    font = ImageFont.load_default(size=28)
    font_small = ImageFont.load_default(size=20)
except TypeError:
    font = ImageFont.load_default()
    font_small = font

bar_area_top = PANEL_H + 60
bar_area_h = 180
bar_max_h = bar_area_h
values = [
    ("LEFT\nwhole image", left_whole, (0.75, 0.65, 0.20)),
    ("LEFT\nsmall tiles",  left_tile,  (0.4, 0.35, 0.15)),
    ("RIGHT\nwhole image", right_whole, (0.10, 0.55, 0.75)),
    ("RIGHT\nsmall tiles", right_tile,  (0.08, 0.30, 0.42)),
]
n_bars = len(values)
bar_w = 140
gap = 90
total_w = n_bars * bar_w + (n_bars - 1) * gap
start_x = (CANVAS_W - total_w) // 2

for i, (label, ratio, color) in enumerate(values):
    x0 = start_x + i * (bar_w + gap)
    h = int(np.clip(ratio, 0.0, 1.0) * bar_max_h)
    y1 = bar_area_top + bar_area_h
    y0 = y1 - h
    col = tuple(int(255*c) for c in color)
    draw.rectangle([x0, bar_area_top, x0+bar_w, y1], outline=(90,90,100), width=2)
    draw.rectangle([x0, y0, x0+bar_w, y1], fill=col)
    pct_txt = f"{ratio*100:.1f}%"
    draw.text((x0 + bar_w/2, y1 + 14), pct_txt, fill=(230,230,230), font=font, anchor="ma")
    draw.multiline_text((x0 + bar_w/2, y1 + 50), label, fill=(150,150,160), font=font_small,
                          anchor="ma", align="center")

draw.text((CANVAS_W/2, 28), "PURPOSE AND PATTERN", fill=(235,235,235), font=font, anchor="ma")
draw.text((CANVAS_W/2, PANEL_H + 10),
          "compressed size / original size  (LZMA, preset 6)",
          fill=(150,150,160), font=font_small, anchor="ma")

img.save('/home/user/claude-mythos-self-play/art_nifty/04_purpose_and_pattern.png')
print("saved 04")
